<?php
/**
 * Diagnostics report.
 *
 * @package WPASL
 */

namespace WPASL\Diagnostics;

use WPASL\Llms\LlmsTxtBuilder;
use WPASL\Robots\Policy;
use WPASL\Signals\ContentSignals;

/**
 * Turns raw probe results into labelled checks (ok / warning / error) and infrastructure findings.
 */
final class Report {

	const TRANSIENT = 'wpasl_diagnostics_report';
	const TTL       = HOUR_IN_SECONDS;

	const OK = 'ok';

	/**
	 * Status of a check this version knows but a stored (older) report does not carry.
	 */
	const NOT_AVAILABLE = 'na';

	/**
	 * Per-crawler check keys produced by this version.
	 *
	 * @var string[]
	 */
	const CRAWLER_CHECKS = array( 'robots', 'home', 'post_html', 'content_signal', 'alternate_link', 'negotiation', 'robots_fetch', 'markdown_url' );
	const WARNING        = 'warning';
	const ERROR          = 'error';

	/**
	 * Policy.
	 *
	 * @var Policy
	 */
	private $policy;

	/**
	 * Signals.
	 *
	 * @var ContentSignals
	 */
	private $signals;

	/**
	 * Constructor.
	 *
	 * @param Policy         $policy  Policy.
	 * @param ContentSignals $signals Signals.
	 */
	public function __construct( Policy $policy, ContentSignals $signals ) {
		$this->policy  = $policy;
		$this->signals = $signals;
	}

	/**
	 * Builds the report from raw probe results.
	 *
	 * @param array<string, mixed> $raw Probe results.
	 * @return array<string, mixed>
	 */
	public function build( array $raw ) {
		$report = array(
			'version'        => WPASL_VERSION,
			'generated_at'   => isset( $raw['generated_at'] ) ? (int) $raw['generated_at'] : time(),
			'sample_post'    => isset( $raw['sample_post'] ) ? (int) $raw['sample_post'] : 0,
			'infrastructure' => $this->infrastructure( $raw ),
			'site'           => $this->site_checks( $raw ),
			'crawlers'       => array(),
		);
		$robots = isset( $raw['site']['robots'] ) ? (array) $raw['site']['robots'] : array();
		foreach ( (array) ( isset( $raw['crawlers'] ) ? $raw['crawlers'] : array() ) as $agent => $checks ) {
			$report['crawlers'][ $agent ] = $this->crawler_checks( $agent, (array) $checks, $report['infrastructure'], $robots );
		}
		return $report;
	}

	/**
	 * Stores a report for one hour.
	 *
	 * @param array<string, mixed> $report Report.
	 * @return void
	 */
	public static function save( array $report ) {
		set_transient( self::TRANSIENT, $report, self::TTL );
	}

	/**
	 * Loads the stored report.
	 *
	 * @return array<string, mixed>|null
	 */
	public static function load() {
		$report = get_transient( self::TRANSIENT );
		return is_array( $report ) ? self::normalize( $report ) : null;
	}

	/**
	 * Default shape of a report, used to render one stored by an earlier plugin version without notices.
	 *
	 * @return array<string, mixed>
	 */
	public static function defaults() {
		return array(
			'version'        => '',
			'generated_at'   => 0,
			'sample_post'    => 0,
			'infrastructure' => array(
				'cdn'               => '',
				'server'            => '',
				'edge_markdown'     => false,
				'storage_exposed'   => false,
				'page_cache'        => '',
				'page_cache_served' => false,
			),
			'site'           => array(),
			'crawlers'       => array(),
		);
	}

	/**
	 * Fills the keys a stored report may lack (the transient survives plugin updates) and marks the
	 * per-crawler checks this version knows but the report does not carry as not available.
	 *
	 * @param array<string, mixed> $report Stored report.
	 * @return array<string, mixed>
	 */
	public static function normalize( array $report ) {
		$defaults                 = self::defaults();
		$report                   = wp_parse_args( $report, $defaults );
		$report['infrastructure'] = wp_parse_args( (array) $report['infrastructure'], $defaults['infrastructure'] );
		$report['site']           = array_map( array( __CLASS__, 'normalize_check' ), (array) $report['site'] );

		$missing  = self::check( self::NOT_AVAILABLE, __( 'Not available in this report (generated by an earlier version). Run the diagnostics again.', 'wp-agent-support-layer' ) );
		$crawlers = array();
		foreach ( (array) $report['crawlers'] as $agent => $data ) {
			$data           = wp_parse_args(
				(array) $data,
				array(
					'policy' => 'allow',
					'checks' => array(),
				)
			);
			$data['checks'] = array_map( array( __CLASS__, 'normalize_check' ), (array) $data['checks'] );
			foreach ( self::CRAWLER_CHECKS as $key ) {
				if ( ! isset( $data['checks'][ $key ] ) ) {
					$data['checks'][ $key ] = $missing;
				}
			}
			$crawlers[ $agent ] = $data;
		}
		$report['crawlers'] = $crawlers;
		return $report;
	}

	/**
	 * Ensures a check has a status and a message.
	 *
	 * @param mixed $check Stored check.
	 * @return array{status:string, message:string}
	 */
	private static function normalize_check( $check ) {
		$check = (array) $check;
		return array(
			'status'  => isset( $check['status'] ) ? (string) $check['status'] : self::NOT_AVAILABLE,
			'message' => isset( $check['message'] ) ? (string) $check['message'] : '',
		);
	}

	/**
	 * CDN / proxy detection, page cache detection and edge-conversion warning.
	 *
	 * @param array<string, mixed> $raw Probe results.
	 * @return array<string, mixed>
	 */
	private function infrastructure( array $raw ) {
		$info = array(
			'cdn'               => '',
			'server'            => '',
			'edge_markdown'     => false,
			'storage_exposed'   => false,
			'page_cache'        => '',
			'page_cache_served' => false,
		);

		$all = array();
		foreach ( (array) ( isset( $raw['site'] ) ? $raw['site'] : array() ) as $result ) {
			$all[] = $result;
		}
		foreach ( (array) ( isset( $raw['crawlers'] ) ? $raw['crawlers'] : array() ) as $checks ) {
			foreach ( (array) $checks as $result ) {
				$all[] = $result;
			}
		}

		foreach ( $all as $result ) {
			$headers = isset( $result['headers'] ) ? (array) $result['headers'] : array();
			if ( isset( $headers['cf-ray'] ) || isset( $headers['cf-cache-status'] ) ) {
				$info['cdn'] = 'Cloudflare';
			} elseif ( '' === $info['cdn'] && ( isset( $headers['x-cache'] ) || isset( $headers['via'] ) || isset( $headers['x-served-by'] ) ) ) {
				$info['cdn'] = isset( $headers['via'] ) ? $headers['via'] : ( isset( $headers['x-served-by'] ) ? $headers['x-served-by'] : $headers['x-cache'] );
			}
			if ( '' === $info['server'] && isset( $headers['server'] ) ) {
				$info['server'] = $headers['server'];
			}
			if ( isset( $headers['x-cache-handler'] ) ) {
				$info['page_cache_served'] = true;
				$label                     = PageCache::label( $headers['x-cache-handler'] );
				if ( '' === $info['page_cache'] || PageCache::CACHE_ENABLER_NAME === $label ) {
					$info['page_cache'] = $label;
				}
			}
		}

		// Cache Enabler active at the time of the run (recorded by the probe) counts even when the web server
		// served the cache files without PHP, so no response carried X-Cache-Handler.
		if ( PageCache::is_cache_enabler( isset( $raw['page_cache'] ) ? $raw['page_cache'] : null ) ) {
			$info['page_cache'] = PageCache::CACHE_ENABLER_NAME;
		}

		if ( 'Cloudflare' === $info['cdn'] ) {
			foreach ( (array) ( isset( $raw['crawlers'] ) ? $raw['crawlers'] : array() ) as $checks ) {
				$md = isset( $checks['post_markdown'] ) ? (array) $checks['post_markdown'] : array();
				if ( self::is_markdown( $md ) && ! self::has_canonical_link( $md ) ) {
					$info['edge_markdown'] = true;
					break;
				}
			}
		}

		if ( isset( $raw['site']['storage'] ) ) {
			$info['storage_exposed'] = 200 === (int) $raw['site']['storage']['status'];
		}

		return $info;
	}

	/**
	 * Site-wide checks.
	 *
	 * @param array<string, mixed> $raw Probe results.
	 * @return array<string, array{status:string, message:string}>
	 */
	private function site_checks( array $raw ) {
		$site   = (array) ( isset( $raw['site'] ) ? $raw['site'] : array() );
		$checks = array();

		$expect = array(
			'robots' => array( 'text/plain', __( 'robots.txt', 'wp-agent-support-layer' ) ),
			'llms'   => array( 'text/markdown', __( 'llms.txt', 'wp-agent-support-layer' ) ),
		);
		// One check per per-type file present in the results, whatever the post types enabled when probing
		// (a report stored by an earlier version carries none).
		foreach ( array_keys( $site ) as $key ) {
			if ( 0 === strpos( (string) $key, 'llms-' ) ) {
				$expect[ $key ] = array( 'text/markdown', $key . '.txt' );
			}
		}
		$expect += array(
			'auth'         => array( 'text/markdown', __( 'auth.md', 'wp-agent-support-layer' ) ),
			'skills'       => array( 'application/ld+json', __( 'agent-skills.json', 'wp-agent-support-layer' ) ),
			'catalog'      => array( 'application/linkset+json', __( 'API catalog', 'wp-agent-support-layer' ) ),
			'markdown_url' => array( 'text/markdown', __( 'Markdown URL of the sample item', 'wp-agent-support-layer' ) ),
		);
		foreach ( $expect as $key => $spec ) {
			if ( ! isset( $site[ $key ] ) ) {
				continue;
			}
			$result = (array) $site[ $key ];
			$type   = isset( $result['headers']['content-type'] ) ? $result['headers']['content-type'] : '';
			if ( self::is_redirect( $result ) ) {
				$checks[ $key ] = self::check( self::WARNING, self::redirect_message( $spec[1], $result ) );
			} elseif ( 200 !== (int) $result['status'] ) {
				$checks[ $key ] = self::check( self::ERROR, sprintf( /* translators: 1: target, 2: HTTP status, 3: error message. */ __( '%1$s: HTTP %2$s %3$s', 'wp-agent-support-layer' ), $spec[1], $result['status'], $result['error'] ) );
			} elseif ( false === stripos( $type, $spec[0] ) ) {
				$checks[ $key ] = self::check( self::WARNING, sprintf( /* translators: 1: target, 2: Content-Type received, 3: Content-Type expected. */ __( '%1$s: unexpected Content-Type "%2$s" (expected %3$s).', 'wp-agent-support-layer' ), $spec[1], $type, $spec[0] ) );
			} elseif ( 'llms' === $key && isset( $result['body_length'] ) && (int) $result['body_length'] > LlmsTxtBuilder::RECOMMENDED_MAX_CHARS ) {
				$checks[ $key ] = self::check(
					self::WARNING,
					sprintf(
						/* translators: 1: Content-Type, 2: size in characters, 3: recommended maximum in characters. */
						__( 'llms.txt: HTTP 200, %1$s, but %2$s characters; agents expect at most %3$s. Lower "Items per section in llms.txt".', 'wp-agent-support-layer' ),
						$type,
						number_format_i18n( (int) $result['body_length'] ),
						number_format_i18n( LlmsTxtBuilder::RECOMMENDED_MAX_CHARS )
					)
				);
			} else {
				$checks[ $key ] = self::check( self::OK, sprintf( /* translators: 1: target, 2: Content-Type. */ __( '%1$s: HTTP 200, %2$s.', 'wp-agent-support-layer' ), $spec[1], $type ) );
			}
		}//end foreach

		if ( isset( $site['render'] ) ) {
			$checks['render'] = self::render_check( (array) $site['render'] );
		}

		if ( isset( $site['storage'] ) ) {
			$exposed           = 200 === (int) $site['storage']['status'];
			$checks['storage'] = $exposed
				? self::check( self::ERROR, __( 'Generated documents are publicly accessible by direct URL. Apache: keep the .htaccess in uploads/wp-agent-support-layer. Nginx: add "location ^~ /wp-content/uploads/wp-agent-support-layer/ { deny all; }".', 'wp-agent-support-layer' ) )
				: self::check( self::OK, __( 'Direct access to the generated documents is denied.', 'wp-agent-support-layer' ) );
		}

		return $checks;
	}

	/**
	 * Check of the render request of the sample item (the loopback that fetches rendered pages): HTTP 200,
	 * text/html and a content region found with the extraction the generation uses.
	 *
	 * @param array<string, mixed> $result Raw result.
	 * @return array{status:string, message:string}
	 */
	private static function render_check( array $result ) {
		$label    = __( 'Rendered page (loopback)', 'wp-agent-support-layer' );
		$type     = isset( $result['headers']['content-type'] ) ? (string) $result['headers']['content-type'] : '';
		$status   = (int) ( isset( $result['status'] ) ? $result['status'] : 0 );
		$error    = isset( $result['error'] ) ? (string) $result['error'] : '';
		$fallback = __( 'the site cannot fetch its own pages, items whose content source is the rendered page are served with the editor content', 'wp-agent-support-layer' );

		if ( self::is_redirect( $result ) ) {
			return self::check( self::WARNING, self::redirect_message( $label, $result ) );
		}
		if ( 200 !== $status || '' !== $error ) {
			return self::check( self::ERROR, sprintf( /* translators: 1: target, 2: HTTP status, 3: error message, 4: consequence. */ __( '%1$s: HTTP %2$s %3$s; %4$s.', 'wp-agent-support-layer' ), $label, $status, $error, $fallback ) );
		}
		if ( false !== stripos( $type, 'text/markdown' ) ) {
			return self::check( self::ERROR, sprintf( /* translators: 1: target, 2: consequence. */ __( '%1$s: the response was text/markdown, the render marker was ignored; %2$s.', 'wp-agent-support-layer' ), $label, $fallback ) );
		}
		if ( false === stripos( $type, 'text/html' ) ) {
			return self::check( self::WARNING, sprintf( /* translators: 1: target, 2: Content-Type received, 3: Content-Type expected. */ __( '%1$s: unexpected Content-Type "%2$s" (expected %3$s).', 'wp-agent-support-layer' ), $label, $type, 'text/html' ) );
		}
		$region = isset( $result['content_region'] ) ? (string) $result['content_region'] : '';
		if ( '' === $region ) {
			return self::check( self::WARNING, sprintf( /* translators: 1: target, 2: Content-Type. */ __( '%1$s: HTTP 200, %2$s, but no content region found (main, [role="main"], article, #content, #primary, .site-content); the whole body would be used. Set the content selector in the General tab.', 'wp-agent-support-layer' ), $label, $type ) );
		}
		return self::check( self::OK, sprintf( /* translators: 1: target, 2: Content-Type, 3: CSS selector. */ __( '%1$s: HTTP 200, %2$s, content region %3$s.', 'wp-agent-support-layer' ), $label, $type, $region ) );
	}

	/**
	 * Checks for one crawler.
	 *
	 * @param string               $agent  Agent token.
	 * @param array<string, mixed> $checks Raw results.
	 * @param array<string, mixed> $infra  Infrastructure findings.
	 * @param array<string, mixed> $robots Raw result of the served /robots.txt.
	 * @return array<string, mixed>
	 */
	private function crawler_checks( $agent, array $checks, array $infra, array $robots = array() ) {
		$policy = $this->policy->for_agent( $agent );
		$out    = array(
			'policy' => $policy,
			'checks' => array( 'robots' => $this->robots_check( $agent, $policy, $robots ) ),
		);

		foreach ( array( 'home', 'post_html' ) as $key ) {
			if ( ! isset( $checks[ $key ] ) ) {
				continue;
			}
			$result = (array) $checks[ $key ];
			$label  = 'home' === $key ? __( 'Home page', 'wp-agent-support-layer' ) : __( 'Sample item (HTML)', 'wp-agent-support-layer' );
			if ( 200 === (int) $result['status'] ) {
				$out['checks'][ $key ] = self::check( self::OK, sprintf( /* translators: %s: target. */ __( '%s: HTTP 200.', 'wp-agent-support-layer' ), $label ) );
			} elseif ( self::is_redirect( $result ) ) {
				$out['checks'][ $key ] = self::check( self::WARNING, self::redirect_message( $label, $result ) );
			} elseif ( in_array( (int) $result['status'], array( 403, 429, 503 ), true ) ) {
				$out['checks'][ $key ] = self::check( self::ERROR, sprintf( /* translators: 1: target, 2: HTTP status. */ __( '%1$s: HTTP %2$d. A WAF, rate limit or bot filter is blocking this user-agent.', 'wp-agent-support-layer' ), $label, $result['status'] ) );
			} else {
				$out['checks'][ $key ] = self::check( self::ERROR, sprintf( /* translators: 1: target, 2: HTTP status, 3: error message. */ __( '%1$s: HTTP %2$s %3$s', 'wp-agent-support-layer' ), $label, $result['status'], $result['error'] ) );
			}
		}

		$cache_enabler = isset( $infra['page_cache'] ) && PageCache::CACHE_ENABLER_NAME === $infra['page_cache'];

		if ( isset( $checks['post_html'] ) ) {
			$html                            = (array) $checks['post_html'];
			$headers                         = (array) $html['headers'];
			$out['checks']['content_signal'] = isset( $headers['content-signal'] )
				? self::check( self::OK, sprintf( /* translators: %s: header value. */ __( 'Content-Signal: %s', 'wp-agent-support-layer' ), $headers['content-signal'] ) )
				: self::check( self::WARNING, $cache_enabler ? self::cache_enabler_missing_header( __( 'Content-Signal header missing on the HTML response.', 'wp-agent-support-layer' ), $headers ) : __( 'Content-Signal header missing on the HTML response (a cache or proxy may strip it).', 'wp-agent-support-layer' ) );

			if ( ! $this->signals->allows_training() ) {
				$out['checks']['x_robots_tag'] = isset( $headers['x-robots-tag'] ) && false !== stripos( $headers['x-robots-tag'], 'noai' )
					? self::check( self::OK, sprintf( /* translators: %s: header value. */ __( 'X-Robots-Tag: %s', 'wp-agent-support-layer' ), $headers['x-robots-tag'] ) )
					: self::check( self::WARNING, $cache_enabler ? self::cache_enabler_missing_header( __( 'X-Robots-Tag noai missing on the HTML response.', 'wp-agent-support-layer' ), $headers ) : __( 'X-Robots-Tag noai missing on the HTML response.', 'wp-agent-support-layer' ) );
			}

			$has_link                        = ! empty( $html['has_md_link'] ) || ( isset( $headers['link'] ) && false !== stripos( $headers['link'], 'text/markdown' ) );
			$out['checks']['alternate_link'] = $has_link
				? self::check( self::OK, __( 'Markdown alternate link present.', 'wp-agent-support-layer' ) )
				: self::check( self::WARNING, __( 'No link rel="alternate" type="text/markdown" found (theme without wp_head, or headers stripped).', 'wp-agent-support-layer' ) );
		}

		if ( isset( $checks['robots'] ) ) {
			$result = (array) $checks['robots'];
			$label  = __( 'robots.txt', 'wp-agent-support-layer' );
			if ( 200 === (int) $result['status'] ) {
				$out['checks']['robots_fetch'] = self::check( self::OK, sprintf( /* translators: %s: target. */ __( '%s: HTTP 200.', 'wp-agent-support-layer' ), $label ) );
			} elseif ( self::is_redirect( $result ) ) {
				$out['checks']['robots_fetch'] = self::check( self::WARNING, self::redirect_message( $label, $result ) );
			} else {
				$out['checks']['robots_fetch'] = self::check( self::ERROR, sprintf( /* translators: 1: target, 2: HTTP status, 3: error message. */ __( '%1$s: HTTP %2$s %3$s. This user-agent cannot read the crawl rules.', 'wp-agent-support-layer' ), $label, $result['status'], $result['error'] ) );
			}
		}

		if ( isset( $checks['post_md'] ) ) {
			$md = (array) $checks['post_md'];
			if ( self::is_markdown( $md ) ) {
				$out['checks']['markdown_url'] = self::check( self::OK, __( 'Markdown URL (.md) served.', 'wp-agent-support-layer' ) );
			} elseif ( 200 === (int) $md['status'] ) {
				$out['checks']['markdown_url'] = self::check( self::ERROR, __( 'The Markdown URL (.md) returned something other than text/markdown; a cache, CDN or rewrite rule is interfering for this user-agent.', 'wp-agent-support-layer' ) );
			} elseif ( self::is_redirect( $md ) ) {
				$out['checks']['markdown_url'] = self::check( self::WARNING, self::redirect_message( __( 'Markdown URL (.md)', 'wp-agent-support-layer' ), $md ) );
			} else {
				$out['checks']['markdown_url'] = self::check( self::ERROR, sprintf( /* translators: 1: HTTP status, 2: error message. */ __( 'Markdown URL (.md) -> HTTP %1$s %2$s. A WAF, rate limit or bot filter is blocking this user-agent on .md URLs.', 'wp-agent-support-layer' ), $md['status'], $md['error'] ) );
			}
		}

		if ( isset( $checks['post_markdown'] ) ) {
			$md = (array) $checks['post_markdown'];
			if ( self::is_markdown( $md ) ) {
				$message = __( 'Markdown served for Accept: text/markdown.', 'wp-agent-support-layer' );
				if ( ! empty( $infra['edge_markdown'] ) && ! self::has_canonical_link( $md ) ) {
					$out['checks']['negotiation'] = self::check( self::WARNING, $message . ' ' . __( 'It appears to be converted by Cloudflare "Markdown for Agents" instead of this plugin; keep only one of the two.', 'wp-agent-support-layer' ) );
				} else {
					$out['checks']['negotiation'] = self::check( self::OK, $message );
				}
			} elseif ( 200 === (int) $md['status'] ) {
				$out['checks']['negotiation'] = self::check(
					self::ERROR,
					$cache_enabler
						? __( 'HTML returned for Accept: text/markdown: Cache Enabler served the cached HTML because its cache key ignores Accept; agents can still use the .md URL. See the page cache notice.', 'wp-agent-support-layer' )
						: __( 'HTML returned for Accept: text/markdown. A page cache or CDN that ignores "Vary: Accept" is probably interfering; agents can still use the .md URL.', 'wp-agent-support-layer' )
				);
			} else {
				$out['checks']['negotiation'] = self::check( self::ERROR, sprintf( /* translators: 1: HTTP status, 2: error message. */ __( 'Accept: text/markdown -> HTTP %1$s %2$s', 'wp-agent-support-layer' ), $md['status'], $md['error'] ) );
			}
		}

		return $out;
	}

	/**
	 * Message of a header missing on an HTML response when Cache Enabler is the page cache: names it as the
	 * probable cause, distinguishing a response it served from its cache (X-Cache-Handler present) from the
	 * mode in which the web server serves the cache files without PHP.
	 *
	 * @param string                $missing Sentence naming the missing header.
	 * @param array<string, string> $headers Response headers.
	 * @return string
	 */
	private static function cache_enabler_missing_header( $missing, array $headers ) {
		if ( isset( $headers['x-cache-handler'] ) ) {
			return $missing . ' ' . __( 'Cache Enabler served it from its page cache, which drops the headers this plugin sends; see the page cache notice.', 'wp-agent-support-layer' );
		}
		return $missing . ' ' . __( 'Cache Enabler is active and its page cache drops the headers this plugin sends; see the page cache notice.', 'wp-agent-support-layer' );
	}

	/**
	 * Compares the configured policy with the verdict of the robots.txt that is actually served.
	 *
	 * @param string               $agent  Agent token.
	 * @param string               $policy Configured policy (allow or block).
	 * @param array<string, mixed> $robots Raw result of the served /robots.txt.
	 * @return array{status:string, message:string}
	 */
	private function robots_check( $agent, $policy, array $robots ) {
		$configured = Policy::BLOCK === $policy ? __( 'block', 'wp-agent-support-layer' ) : __( 'allow', 'wp-agent-support-layer' );

		if ( 200 !== (int) ( isset( $robots['status'] ) ? $robots['status'] : 0 ) || ! isset( $robots['body'] ) ) {
			return self::check(
				self::WARNING,
				sprintf(
					/* translators: 1: HTTP status, 2: configured policy. */
					__( 'robots.txt could not be read (HTTP %1$s), so the served rules were not verified; the configured policy is "%2$s".', 'wp-agent-support-layer' ),
					isset( $robots['status'] ) ? $robots['status'] : 0,
					$configured
				)
			);
		}

		$served = self::robots_verdict( (string) $robots['body'], $agent );
		if ( null === $served ) {
			return self::check(
				self::WARNING,
				sprintf(
					/* translators: 1: crawler token, 2: configured policy. */
					__( 'No rule for %1$s in the served robots.txt (configured policy: "%2$s"). A physical robots.txt or a cache may be serving stale rules.', 'wp-agent-support-layer' ),
					$agent,
					$configured
				)
			);
		}
		if ( $served !== $policy ) {
			return self::check(
				self::WARNING,
				sprintf(
					/* translators: 1: served verdict, 2: crawler token, 3: configured policy. */
					__( 'The served robots.txt says "%1$s" for %2$s but the configured policy is "%3$s". A physical robots.txt or a cache may be serving stale rules.', 'wp-agent-support-layer' ),
					Policy::BLOCK === $served ? __( 'block', 'wp-agent-support-layer' ) : __( 'allow', 'wp-agent-support-layer' ),
					$agent,
					$configured
				)
			);
		}
		return Policy::BLOCK === $policy
			? self::check( self::OK, __( 'Blocked by robots.txt, as configured.', 'wp-agent-support-layer' ) )
			: self::check( self::OK, __( 'Allowed by robots.txt, as configured.', 'wp-agent-support-layer' ) );
	}

	/**
	 * Verdict of a robots.txt body for one user-agent token: "block" when its group disallows the whole
	 * site, "allow" when the group exists and does not, null when no group names the token.
	 *
	 * Groups follow RFC 9309: consecutive User-agent lines share the rules that follow them; a new
	 * User-agent line after a rule starts a new group; "User-agent: *" never counts as the token's group.
	 *
	 * @param string $body  robots.txt body.
	 * @param string $agent Agent token.
	 * @return string|null
	 */
	public static function robots_verdict( $body, $agent ) {
		$groups  = array();
		$current = null;
		foreach ( preg_split( '/\r\n|\r|\n/', (string) $body ) as $line ) {
			$line = trim( (string) preg_replace( '/#.*$/', '', $line ) );
			if ( '' === $line || ! preg_match( '/^([a-z-]+)\s*:\s*(.*)$/i', $line, $m ) ) {
				continue;
			}
			$field = strtolower( $m[1] );
			$value = trim( $m[2] );
			if ( 'user-agent' === $field ) {
				if ( null === $current || ! empty( $current['rules'] ) ) {
					if ( null !== $current ) {
						$groups[] = $current;
					}
					$current = array(
						'agents' => array(),
						'rules'  => array(),
					);
				}
				$current['agents'][] = strtolower( $value );
			} elseif ( null !== $current && in_array( $field, array( 'allow', 'disallow' ), true ) ) {
				$current['rules'][] = array( $field, $value );
			}
		}//end foreach
		if ( null !== $current ) {
			$groups[] = $current;
		}

		$token   = strtolower( $agent );
		$verdict = null;
		foreach ( $groups as $group ) {
			if ( ! in_array( $token, $group['agents'], true ) ) {
				continue;
			}
			$verdict = Policy::ALLOW;
			foreach ( $group['rules'] as $rule ) {
				if ( 'allow' === $rule[0] && '/' === $rule[1] ) {
					return Policy::ALLOW;
					// An explicit root Allow wins (equal-length match, RFC 9309 5.2).
				}
				if ( 'disallow' === $rule[0] && '/' === $rule[1] ) {
					$verdict = Policy::BLOCK;
				}
			}
		}
		return $verdict;
	}

	/**
	 * Whether a result is a redirect (never followed by the probe).
	 *
	 * @param array<string, mixed> $result Result.
	 * @return bool
	 */
	private static function is_redirect( array $result ) {
		$status = (int) ( isset( $result['status'] ) ? $result['status'] : 0 );
		return $status >= 300 && $status < 400;
	}

	/**
	 * Warning text for a redirected target.
	 *
	 * @param string               $label  Target label.
	 * @param array<string, mixed> $result Result.
	 * @return string
	 */
	private static function redirect_message( $label, array $result ) {
		$location = isset( $result['headers']['location'] ) ? (string) $result['headers']['location'] : '';
		return sprintf(
			/* translators: 1: target label, 2: HTTP status, 3: Location header. */
			__( '%1$s: HTTP %2$d redirect to %3$s. The diagnostics never follow redirects; crawlers may not either. Serve the content on the canonical host.', 'wp-agent-support-layer' ),
			$label,
			(int) $result['status'],
			'' === $location ? __( '(no Location header)', 'wp-agent-support-layer' ) : $location
		);
	}

	/**
	 * Whether a result is a Markdown response.
	 *
	 * @param array<string, mixed> $result Result.
	 * @return bool
	 */
	private static function is_markdown( array $result ) {
		return 200 === (int) ( isset( $result['status'] ) ? $result['status'] : 0 )
			&& isset( $result['headers']['content-type'] )
			&& false !== stripos( $result['headers']['content-type'], 'text/markdown' );
	}

	/**
	 * Whether a result carries this plugin's canonical Link header (absent when converted at the edge).
	 *
	 * @param array<string, mixed> $result Result.
	 * @return bool
	 */
	private static function has_canonical_link( array $result ) {
		return isset( $result['headers']['link'] ) && false !== stripos( $result['headers']['link'], 'rel="canonical"' );
	}

	/**
	 * Builds a check entry.
	 *
	 * @param string $status  ok, warning or error.
	 * @param string $message Message.
	 * @return array{status:string, message:string}
	 */
	private static function check( $status, $message ) {
		return array(
			'status'  => $status,
			'message' => $message,
		);
	}
}
