<?php
/**
 * Builds auth.md.
 *
 * @package WPASL
 */

namespace WPASL\Manifest;

use WPASL\Generation\ArtifactGeneratorInterface;
use WPASL\Markdown\Delivery;
use WPASL\Markdown\DocumentBuilder;
use WPASL\Settings;
use WPASL\Signals\ContentSignals;
use WPASL\Storage;

/**
 * The public access statement served at /auth.md: who the audience is, that there is no registration nor
 * credential provisioning, and which public read-only endpoints and discovery documents the site offers.
 *
 * The template is written in English on purpose and does not go through the translation functions: the
 * readers are agents and scanners looking for fixed phrases such as "no registration". Capability names
 * and descriptions come from the registry and follow the site language.
 */
final class AuthMdBuilder implements ArtifactGeneratorInterface {

	const FILE = 'auth.md';

	/**
	 * Settings.
	 *
	 * @var Settings
	 */
	private $settings;

	/**
	 * Registry.
	 *
	 * @var CapabilityRegistry
	 */
	private $registry;

	/**
	 * Signals.
	 *
	 * @var ContentSignals
	 */
	private $signals;

	/**
	 * Constructor.
	 *
	 * @param Settings           $settings Settings.
	 * @param CapabilityRegistry $registry Registry.
	 * @param ContentSignals     $signals  Signals.
	 */
	public function __construct( Settings $settings, CapabilityRegistry $registry, ContentSignals $signals ) {
		$this->settings = $settings;
		$this->registry = $registry;
		$this->signals  = $signals;
	}

	/**
	 * Artifact id.
	 *
	 * @return string
	 */
	public function id() {
		return 'auth-md';
	}

	/**
	 * Whether auth.md is published: the manifests are enabled and the auth.md box is checked.
	 *
	 * @param Settings $settings Settings.
	 * @return bool
	 */
	public static function is_published( Settings $settings ) {
		return (bool) $settings->get( 'manifest_enabled' ) && (bool) $settings->get( 'auth_md_enabled' );
	}

	/**
	 * Whether auth.md is published.
	 *
	 * @return bool
	 */
	public function enabled() {
		return self::is_published( $this->settings );
	}

	/**
	 * Writes auth.md, or removes it when disabled.
	 *
	 * @param Storage $storage Storage.
	 * @return void
	 */
	public function generate( Storage $storage ) {
		if ( ! $this->enabled() ) {
			$storage->delete( self::FILE );
			return;
		}
		$storage->write( self::FILE, $this->document() );
	}

	/**
	 * Absolute URL of auth.md.
	 *
	 * @return string
	 */
	public static function url() {
		return home_url( '/' . self::FILE );
	}

	/**
	 * The auth.md document.
	 *
	 * @return string
	 */
	public function document() {
		$site_name = DocumentBuilder::plain_text( get_bloginfo( 'name' ) );
		$home      = home_url( '/' );
		$pretty    = '' !== (string) get_option( 'permalink_structure' );

		$out  = '# ' . $site_name . " auth.md\n\n";
		$out .= '> How automated agents may access ' . $home . ". Generated by WP Agent Support Layer from the site's current configuration.\n\n";

		$out .= "## Audience\n\n";
		$out .= "AI agents, LLM-based assistants and AI crawlers that read this site's public content.\n\n";

		$when = trim( (string) $this->settings->get( 'llms_when_to_use' ) );
		if ( '' !== $when ) {
			$out .= "## When to use this site\n\n" . $when . "\n\n";
		}

		$out .= "## Registration and credential provisioning\n\n";
		$out .= 'This site does not offer agent registration or credential provisioning. There is no sign-up endpoint, no API key issuance and no authorization server. '
			. "Do not attempt to register, and do not send credentials: every resource listed below is public.\n\n";

		$out .= "## Supported access methods\n\n";
		$out .= "Anonymous HTTP GET requests, without any credential. Send a descriptive User-Agent and honour robots.txt.\n\n";

		$out .= "### Public endpoints\n\n";
		foreach ( $this->registry->all() as $capability ) {
			if ( 'auth-md' === $capability['id'] ) {
				continue;
			}
			$url  = isset( $capability['url'] ) ? $capability['url'] : $capability['urlTemplate'];
			$out .= '- **' . self::inline( $capability['name'] ) . '** — ' . $capability['method'] . ' ' . $url;
			if ( '' !== $capability['description'] ) {
				$out .= ': ' . self::inline( $capability['description'] );
			}
			$out .= "\n";
		}
		$out .= "\n";

		$out .= "### Discovery documents\n\n";
		$out .= '- llms.txt: ' . home_url( '/llms.txt' ) . "\n";
		$out .= '- API catalog (RFC 9727): ' . home_url( '/.well-known/api-catalog' ) . "\n";
		$out .= '- Agent skills (JSON-LD): ' . home_url( '/' . ManifestRouter::SKILLS_PATH ) . "\n";
		$out .= '- OpenAPI 3.1: ' . ManifestBuilder::openapi_url() . "\n";
		$out .= '- Markdown version of any public item: '
			. ( $pretty ? 'append `.md` to its URL' : 'add `?' . Delivery::QUERY_VAR . '=md` to its URL' )
			. ', or request it with `Accept: ' . Delivery::MIME . "`.\n\n";

		$out .= "## Credential use\n\n";
		$out .= 'No credential is required or accepted for the resources above. Authenticated and write operations of the WordPress REST API are not offered to agents; '
			. "they follow WordPress's standard authentication and permission rules and are outside the scope of this document.\n\n";

		$out .= "## API versioning and deprecation\n\n";
		$out .= ManifestBuilder::versioning_policy( ManifestBuilder::namespaces_of( $this->rest_urls() ) ) . "\n\n";

		$signals = $this->signals->values();
		$out    .= "## Usage policy\n\n";
		$out    .= 'Content signals: search=' . $signals['search'] . ', ai-input=' . $signals['ai-input'] . ', ai-train=' . $signals['ai-train'] . '. See ' . home_url( '/robots.txt' ) . ".\n\n";

		$out .= "## Contact\n\n";
		$out .= 'Technical contact: ' . $this->settings->contact_email() . "\n";

		$notes = trim( (string) $this->settings->get( 'auth_md_notes' ) );
		if ( '' !== $notes ) {
			$out .= "\n## Notes\n\n" . $notes . "\n";
		}

		/**
		 * Filters the generated auth.md.
		 *
		 * @param string $out Markdown document.
		 */
		return (string) apply_filters( 'wpasl_auth_md', $out );
	}

	/**
	 * URLs of the capabilities that live under the REST API base.
	 *
	 * @return string[]
	 */
	private function rest_urls() {
		$rest_url = rest_url();
		$urls     = array();
		foreach ( $this->registry->all() as $capability ) {
			$url = isset( $capability['url'] ) ? $capability['url'] : $capability['urlTemplate'];
			if ( 0 === strpos( $url, $rest_url ) ) {
				$urls[] = $url;
			}
		}
		return $urls;
	}

	/**
	 * One-line text for a list item.
	 *
	 * @param string $text Text.
	 * @return string
	 */
	private static function inline( $text ) {
		return trim( (string) preg_replace( '/\s+/', ' ', DocumentBuilder::plain_text( (string) $text ) ) );
	}
}
