<?php
/**
 * File storage for generated documents.
 *
 * @package WPASL
 */

namespace WPASL;

// Generated documents live in the uploads directory, which WordPress itself writes to with
// native filesystem functions; WP_Filesystem adds nothing here but credential prompts.
// phpcs:disable WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents, WordPress.WP.AlternativeFunctions.file_system_operations_mkdir, WordPress.WP.AlternativeFunctions.file_system_operations_rmdir, WordPress.WP.AlternativeFunctions.unlink_unlink, WordPress.WP.AlternativeFunctions.rename_rename, WordPress.PHP.NoSilencedErrors.Discouraged

/**
 * Stores generated files under uploads/wp-agent-support-layer/<token>/ and blocks direct access.
 */
final class Storage {

	const ROOT_DIRNAME = 'wp-agent-support-layer';
	const TOKEN_OPTION = 'wpasl_storage_token';

	/**
	 * Root directory shared by all tokens for this site (no trailing slash).
	 *
	 * @return string
	 */
	public static function root_dir() {
		$uploads = wp_upload_dir( null, false );
		return trailingslashit( $uploads['basedir'] ) . self::ROOT_DIRNAME;
	}

	/**
	 * Per-site random token that makes the storage path unguessable.
	 *
	 * @return string
	 */
	public static function token() {
		$token = get_option( self::TOKEN_OPTION, '' );
		if ( ! is_string( $token ) || ! preg_match( '/^[a-f0-9]{32}$/', $token ) ) {
			$token = md5( wp_generate_password( 64, true, true ) );
			update_option( self::TOKEN_OPTION, $token, false );
		}
		return $token;
	}

	/**
	 * Base directory for this site's documents (no trailing slash).
	 *
	 * @return string
	 */
	public function base_dir() {
		return self::root_dir() . '/' . self::token();
	}

	/**
	 * Absolute path for a relative document path.
	 *
	 * @param string $relative Relative path such as "md/post/12.md".
	 * @return string
	 */
	public function path( $relative ) {
		$relative = ltrim( str_replace( '\\', '/', $relative ), '/' );
		if ( false !== strpos( $relative, '..' ) ) {
			$relative = str_replace( '..', '', $relative );
		}
		return $this->base_dir() . '/' . $relative;
	}

	/**
	 * Creates the directory tree and the files that block direct HTTP access.
	 *
	 * @return bool
	 */
	public function ensure() {
		$root = self::root_dir();
		$base = $this->base_dir();

		if ( ! wp_mkdir_p( $base ) ) {
			return false;
		}

		$guards = array(
			$root . '/index.php' => "<?php\n// Silence is golden.\n",
			$root . '/.htaccess' => "# Generated by WP Agent Support Layer. Documents are served through PHP only.\n<IfModule mod_authz_core.c>\n\tRequire all denied\n</IfModule>\n<IfModule !mod_authz_core.c>\n\tOrder deny,allow\n\tDeny from all\n</IfModule>\n",
			$base . '/index.php' => "<?php\n// Silence is golden.\n",
		);

		foreach ( $guards as $file => $contents ) {
			if ( ! file_exists( $file ) && false === file_put_contents( $file, $contents ) ) {
				return false;
			}
		}

		return true;
	}

	/**
	 * Whether a document exists.
	 *
	 * @param string $relative Relative path.
	 * @return bool
	 */
	public function exists( $relative ) {
		return is_file( $this->path( $relative ) );
	}

	/**
	 * Reads a document.
	 *
	 * @param string $relative Relative path.
	 * @return string|null Null when missing.
	 */
	public function read( $relative ) {
		$path = $this->path( $relative );
		if ( ! is_file( $path ) ) {
			return null;
		}
		$contents = file_get_contents( $path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
		return false === $contents ? null : $contents;
	}

	/**
	 * Modification time of a document.
	 *
	 * @param string $relative Relative path.
	 * @return int|null Unix timestamp or null when missing.
	 */
	public function mtime( $relative ) {
		$path = $this->path( $relative );
		return is_file( $path ) ? (int) filemtime( $path ) : null;
	}

	/**
	 * Writes a document atomically.
	 *
	 * @param string $relative Relative path.
	 * @param string $contents File contents.
	 * @return bool
	 */
	public function write( $relative, $contents ) {
		$path = $this->path( $relative );
		if ( ! wp_mkdir_p( dirname( $path ) ) ) {
			return false;
		}
		$tmp = $path . '.' . wp_generate_password( 8, false ) . '.tmp';
		if ( false === file_put_contents( $tmp, $contents ) ) {
			return false;
		}
		if ( ! @rename( $tmp, $path ) ) {
			@unlink( $tmp );
			return false;
		}
		return true;
	}

	/**
	 * Deletes a document.
	 *
	 * @param string $relative Relative path.
	 * @return bool
	 */
	public function delete( $relative ) {
		$path = $this->path( $relative );
		return ! is_file( $path ) || @unlink( $path );
	}

	/**
	 * Lists documents below a relative directory.
	 *
	 * @param string $relative_dir Relative directory.
	 * @return string[] Relative paths.
	 */
	public function list_files( $relative_dir ) {
		$dir = $this->path( $relative_dir );
		if ( ! is_dir( $dir ) ) {
			return array();
		}
		$found    = array();
		$base_len = strlen( $this->base_dir() ) + 1;
		$iterator = new \RecursiveIteratorIterator( new \RecursiveDirectoryIterator( $dir, \FilesystemIterator::SKIP_DOTS ) );
		foreach ( $iterator as $file ) {
			if ( $file->isFile() && 'php' !== $file->getExtension() ) {
				$found[] = substr( $file->getPathname(), $base_len );
			}
		}
		sort( $found );
		return $found;
	}

	/**
	 * Removes this site's whole storage root, including guards and the token option.
	 *
	 * @return void
	 */
	public static function delete_all() {
		self::rmdir_recursive( self::root_dir() );
		delete_option( self::TOKEN_OPTION );
	}

	/**
	 * Recursively removes a directory.
	 *
	 * @param string $dir Absolute directory.
	 * @return void
	 */
	private static function rmdir_recursive( $dir ) {
		if ( ! is_dir( $dir ) ) {
			return;
		}
		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \FilesystemIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ( $iterator as $item ) {
			if ( $item->isDir() ) {
				@rmdir( $item->getPathname() );
			} else {
				@unlink( $item->getPathname() );
			}
		}
		@rmdir( $dir );
	}
}
